apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ namespace }}
  name: filebeat-template
spec:
  template:
    spec:
      containers:
      - name: filebeat-template
        image: docker.elastic.co/beats/filebeat:7.0.0
        command: [ "filebeat", "setup", "--template",
          "-E", "output.logstash.enabled=false",
          "-E", 'output.elasticsearch.hosts=["elasticsearch.{{ namespace }}.svc.cluster.local:9200"]' ]
      restartPolicy: Never
  backoffLimit: 4
